image: python:3.11-slim

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

# Cache pip dependencies
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest tests/ --cov=src/ --cov-report=term-missing
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

lint:
  stage: test
  script:
    - pip install flake8
    - flake8 src/

build:
  stage: build
  script:
    - docker-compose build
  only:
    - main
    - develop

deploy_staging:
  stage: deploy
  script:
    - docker-compose up -d
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - docker-compose up -d
  environment:
    name: production
  only:
    - main
  when: manual 