version: '3.8'

services:
  # Service principal Python
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bankreports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  # Base de données SQLite (pour le développement)
  db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: sh -c "mkdir -p /data && echo 'SQLite database directory' > /data/README.txt"

  # API FastAPI
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bankreports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Monitoring Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  # Dashboard Grafana
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: 