rules:
  - name: "Include grilleEvaluation"
    match:
      - "parametrage/grilleEvaluation.md"
    actions:
      - includeInPrompt

  - name: "Include consignes"
    match:
      - "parametrage/consignes.md"
    actions:
      - includeInPrompt
